Better error messages when not online

diff --git a/.bin/wallpaper b/.bin/wallpaper
--- a/.bin/wallpaper
+++ b/.bin/wallpaper
@@ -1,7 +1,7 @@
 #!/bin/bash
 #
 # Compose and set a wallpaper from disc, URL or from top images on reddit.com.
-# Edit the last line for a command that sets the wall in your window manager 
+# Edit the last line for a command that sets the wall in your window manager
 #
 # Usage:
 #  Use a local file.
@@ -10,7 +10,7 @@
 #  Fetch and use a file from an URL.
 #    $ wallpaper http://www.somesite.com/with/image.png
 #
-#  Fetch a random current top image from reddit (not marked NSFW). 
+#  Fetch a random current top image from reddit (not marked NSFW).
 #  Edit $REDDITSUBS below to set which subreddits to check for images.
 #    $ wallpaper
 #
@@ -42,7 +42,7 @@ fi
 shift $(($OPTIND-1))
 
 SOURCE="$1"
-if [ "x$SOURCE" == "x" ]; then 
+if [ -z "$SOURCE" ]; then
     # If no $SOURCE is specified, check if we have a fixed, local available
     # (named active.jpg or active.png in ~/.wallpaper)
     SOURCE=~/.wallpaper/active.jpg
@@ -69,6 +69,9 @@ if [ "x$SOURCE" == "x" ]; then
     fi
 fi
 
+if [ -z "$SOURCE" ]; then
+    die "No source image to set"
+fi
 IMAGE=$(basename "$SOURCE")
 
 DIR=$(mktemp -d)
@@ -78,7 +81,7 @@ trap 'rm -rf $DIR' EXIT
 if [ $(echo "$SOURCE" | grep '^[a-z]\+://') ]; then
     wget -q "$SOURCE" -O "$IMAGE" || die "Failed to download $SOURCE to $IMAGE"
 else
-    cp "$SOURCE" "$IMAGE" || die "Failed fo copy $SOURCE to $IMAGE"
+    cp "$SOURCE" "$IMAGE" || die "Failed to copy $SOURCE to $IMAGE"
 fi
 
 DEST="output.png"
